{
 "title": "Demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "id", "label": "Device", "query": "SHOW TAG VALUES WITH KEY = id" }
  ]
 },
 "panels": [
  { "title": "Device $id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "id" },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "temperature",
     "query": "SELECT last(\"co2_concentration\") FROM \"autogen\"./^$id$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "relative-humidity",
     "query": "SELECT last(\"co2_concentration\") FROM \"autogen\"./^$id$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Illuminance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "illuminance",
     "query": "SELECT last(\"co2_concentration\") FROM \"autogen\"./^$id$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "co2",
     "query": "SELECT last(\"co2_concentration\") FROM \"autogen\"./^$id$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pressure",
     "query": "SELECT last(\"value\")/100 FROM \"autogen\".\"pressure\" WHERE \"id\" =~ /^$id$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  { "title": "Temperature graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Temperature [°C]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_id - $tag_channel",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT mean(\"value\") AS \"$field\" FROM \"temperature\" WHERE \"device_id\" =~ /^$id$/ AND $timeFilter GROUP BY time($__interval), \"id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$field" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  { "title": "Relative humidity graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Relative humidity [%]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_id",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "relative-humidity",
     "query": "SELECT mean($field) AS $field FROM \"device\" WHERE \"device_id\" =~ /^$id$/ AND $timeFilter GROUP BY time($__interval), \"device_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$field" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  { "title": "CO2 graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CO2 [ppm]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_id",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2",
     "query": "SELECT mean($field) AS $field FROM \"device\" WHERE \"device_id\" =~ /^$id$/ AND $timeFilter GROUP BY time($__interval), \"device_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  { "title": "Illuminance graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Illuminance [lux]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_id",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "illuminance",
     "query": "SELECT mean($field) AS $field FROM \"device\" WHERE \"device_id\" =~ /^$id$/ AND $timeFilter GROUP BY time($__interval), \"device_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$field" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  { "title": "Presure graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Atmospheric pressure [hPa]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_id",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "query": "SELECT mean(\"value\") / 100 AS \"$field\" FROM \"pressure\" WHERE (\"id\" =~ /^$id$/) AND $timeFilter GROUP BY time($__interval), \"id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$field" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  { "title": "Button event count graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Button event count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_id  $tag_channel",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "button",
     "query": "SELECT \"values\" AS \"$field\" FROM \"button\" WHERE (\"id\" =~ /^$id$/) AND $timeFilter GROUP BY time($__interval), \"id\", \"channel\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$field" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  { "title": "Battery graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Battery [V]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_id",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "query": "SELECT mean(\"value\") / 100 AS \"$field\" FROM \"pressure\" WHERE (\"id\" =~ /^$id$/) AND $timeFilter GROUP BY time($__interval), \"id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$field" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  }
 ]
}